In [157]:
import re
import numpy as np
import math

In [2]:
text = "Hello there, I am SJR. I love to sing and dance. My hobby is to listen to the music."

In [3]:
text = " ".join(text.strip().split())
text

'Hello there, I am SJR. I love to sing and dance. My hobby is to listen to the music.'

In [5]:
from nltk.corpus import stopwords

In [9]:
stop_words = stopwords.words('english')

In [18]:
tokenized_text = text.split()

In [29]:
tokenized_text

['Hello',
 'there,',
 'I',
 'am',
 'SJR.',
 'I',
 'love',
 'to',
 'sing',
 'and',
 'dance.',
 'My',
 'hobby',
 'is',
 'to',
 'listen',
 'to',
 'the',
 'music.']

In [30]:
normalized_text = " ".join(text for text in tokenized_text)

In [33]:
normalized_text.lower()

'hello there, i am sjr. i love to sing and dance. my hobby is to listen to the music.'

In [41]:
normalized_text = normalized_text.replace(".","").replace(",","").lower().strip()

In [69]:
normalized_text

'hello there i am sjr i love to sing and dance my hobby is to listen to the music'

## Creating function for ngrams

In [126]:
def ng(text):
    grams = []
    arr = text.split()
    i = 0
    for x in arr:
        temp = (arr[i],arr[i+1])
        grams.insert(i,temp)
        i=i+1 if i<len(arr)-2 else i
    grams = grams[:-1]
    return grams

In [127]:
n_grams = ng(normalized_text)

In [128]:
n_grams

[('hello', 'there'),
 ('there', 'i'),
 ('i', 'am'),
 ('am', 'sjr'),
 ('sjr', 'i'),
 ('i', 'love'),
 ('love', 'to'),
 ('to', 'sing'),
 ('sing', 'and'),
 ('and', 'dance'),
 ('dance', 'my'),
 ('my', 'hobby'),
 ('hobby', 'is'),
 ('is', 'to'),
 ('to', 'listen'),
 ('listen', 'to'),
 ('to', 'the'),
 ('the', 'music')]

## Now, we have to develop the transition matrix

In [160]:
unique_words = list(set(normalized_text.split()))

In [161]:
len(unique_words)

16

In [162]:
tm = np.zeros((len(unique_words),len(unique_words)))

In [163]:
tm

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [183]:
for i,fw in enumerate(unique_words):
    for j,nw in enumerate(unique_words):
        cnt = 0
        for n in n_grams:
            if n[0]==fw and n[1]==nw:
                cnt += 1
        tm[i][j] = cnt

In [184]:
tm

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,

In [185]:
from sklearn.preprocessing import normalize

In [191]:
norm_matrix = normalize(tm,axis=1,norm='l1')

In [192]:
norm_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.5       , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.5       , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33333333, 0.        , 0.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 

## Finally, the Markov Model

In [226]:
def markov_generator(in_word,length):
    initial_word = in_word
    completed_word = ""

    i_word = initial_word

    for i in range(length):
        index = unique_words.index(initial_word)
        best_probable_word_idx = np.argmax(norm_matrix[index])
        best_probable_word = unique_words[best_probable_word_idx]
        completed_word += " " + best_probable_word
        initial_word = best_probable_word
    #print(i_word,completed_word)
    generated_content = i_word+" "+completed_word
    return generated_content

In [227]:
gen = markov_generator("i",5)

In [228]:
print(gen)

i  love to sing and dance
